version: '3'
services:
  jupyter:
    restart       : always
    build         : ./jupyter
    hostname      : 'jupyter'
    container_name: 'jupyter'
    working_dir   : '/opt/jupyter'
    tty           : true
    volumes       :
      - ~/.ssh:/root/.ssh
      - ./jupyter/notebook:/opt/jupyter
    ports         :
      - "8888:8888"
    command       : jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8888

  metabase:
    image         : metabase/metabase
    hostname      : 'metabase'
    container_name: 'metabase'
    volumes:
      - ./metabase/metabase:/metabase.db:cached
    ports:
      - "3000:3000"

  mysql:
    image         : mysql:5.7
    hostname      : 'mysql'
    container_name: 'mysql'
    volumes:
      - ./mysql/mysql.conf.d:/etc/mysql/mysql.conf.d/
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_HOST    : '%'
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '33061:3306'

  mailhog:
    image         : mailhog/mailhog
    hostname      : mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
    volumes       :
      - ./mailhog/auth.file:/auth.file
    command       : -auth-file=/auth.file
