version: '3'
services:
  python3:
    restart: always
    build: .
    hostname      : 'jupyter'
    container_name: 'jupyter'
    working_dir: '/home/python'
    env_file:
      - ./.my.env
    tty: true
    volumes:
      - ~/.ssh:/root/.ssh
      - ./:/home/python
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8888 
