version: '3'
services:
   mysql:
     image: mysql:5.7
     hostname      : 'mysql'
     container_name: 'mysql'
     volumes:
       - ./mysql_data:/var/lib/mysql
       - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
     environment:
       MYSQL_ROOT_HOST    : '%'
       MYSQL_ROOT_PASSWORD: password
     ports:
       - '33061:3306'
